export {default as logo} from './logo2.jpg'
export {default as bg1} from './bg1.jpg'
export {default as bg2} from './bg2.jpg'
export {default as bg3} from './bg3.jpg'
export {default as bg4} from './bg4.jpg'
export {default as notfound} from './404.jpg'